from review import *
p=OUT/'PPG_REVIEW_B.md'
p.write_text(p.read_text(encoding='utf-8')+'''\n## 批次2：scheduler全周期与取消边界\n\n### B-003 — NORMAL宏帧实际周期5001拍，偏离5000拍/400 Hz合同\n\n- S1 / RTL。C08 §4.2:134-142规定2 MHz、5000拍、4999→0进入下一宏帧，§自检FSC-03要求周期。RTL:752-790只在沿前无active时启动；792-846末拍清active、回IDLE，使下一次启动额外占一拍。Top:862-868只传身份位宽，没有覆盖默认5000或补偿周期。\n- 原文（2行）：`C_MACRO_FRAME_TICKS = 5000`；`宏帧计数范围为0..4999，在4999 -> 0时进入下一宏帧。`\n- 仿真：evidence/scheduler_cadence以原RTL/默认参数、始终eligible且所有ready/idle有效连续测得5001、5001、5001；精确5000比较3次FAIL、退出1。evidence/scheduler_cadence_counterfactual只在本组副本把长度改4999，测得3次5000并PASS，定位多余边界拍。后者不是有效修复方案，未改共享RTL。\n- 影响：理想连续NORMAL每色采样约399.920016 Hz，每帧累积一拍相位偏差；不声称任意背压情况下必须保持400 Hz。反驳：输入全就绪排除了外部ADC/消费者等待；CAL rollover有旁路、不能补偿NORMAL。源内恢复预热属于PWI资格，与这个已经eligible的边界空拍不同。置信度：仿真确认默认叶子行为、Top静态直连确认。建议按合同明确连续NORMAL边界进入语义并补严格周期比较；不修复。\n\n### B-004 — scheduler单元TB容许多一拍并跳过真实Q3完成资格\n\n- S2 / TB。TB:581容许`(reg_frame_period == 5000) || (reg_frame_period == 5001)`，不能发现B-003。TB:276把`i_owner_q3_window_closed`恒接1，310-336固定计数DONE模型；C08:1205明确不允许固定4拍DONE替代真实物理完成链。\n- 原文（2行）：`.i_owner_q3_window_closed(1'b1)`；`check_fsc(14, (reg_frame_period == 5000) || (reg_frame_period == 5001));`\n- 仿真负对照：仅去掉RTL:460的Q3成功门控，evidence/scheduler_original_q3_gate_mutant仍59 PASS；补充早DONE且Q3=0场景，原RTL释放owner但不报NORMAL完成（evidence/scheduler_early_q3，owner=2/done=2/normalcomplete=0，PASS），同变异却normalcomplete=1，evidence/scheduler_early_q3_mutant FAIL并退出1。\n- 反驳：本条不指控原RTL Q3逻辑，也不宣称系统LFA/Q3全无覆盖；原TB有真实比较和失败输出，缺陷在资格与允许值。建议精确周期断言和早DONE对照，并将物理链自检交给实际链TB；不修复。置信度：静态+变异实测。\n\n### B-005 — CAL末拍rollover覆盖同拍abort撤销\n\n- S1 / RTL。RTL:468-473的rollover条件没有取消资格；597-619主next虽清STARTED/FRAME_ACTIVE，853-872的后置state_rollover_next再将FRAME_ACTIVE置1并进入CAL、frame_id递增。C08 §16.4要求abort清宏帧，§15事件优先级要求取消阻止新工作。\n- 原文（2行）：`state_rollover_next[B_FRAME_ACTIVE] = 1'b1;`；`if(flag_calibration_rollover)begin`。\n- 最小证据：evidence/scheduler_abort_tick4999中CAL active=1/inflight=0/pending=1/rollover=1，于negedge拉abort、下一posedge检查，active仍1、tick=0、ownercommit=0、idle=0，FAIL退出1；相同刺激提前一拍（evidence/scheduler_abort_tick4998）active=0/idle=1，PASS。固定输入均已初始化，没有沿上驱动竞态。\n- 已证实范围：逻辑CAL上下文在取消沿被重新创建、scheduler不能立即idle；没有观察到新的物理owner，因为STARTED已清且生命周期gate仍阻止commit。不得据此夸大为ADC永远不返回或永久死锁。STOP也共享未门控overlay，额外drain长度仍需专项量化。Top传播静态及系统边界覆盖待核对。置信度：叶子边界仿真确认。建议让rollover服从取消/生命周期优先级并加入相邻拍反证；不修复。\n\n### scheduler其余审阅结果\n\nRTL884行、TB936行与C08合同1252行的功能正文已读。请求资格双边检查、valid载荷冻结、waveform与owner分离、sample_index只在owner提交递增、sample+generation匹配后释放、Q3只门控success、错/重复DONE阻断均核对。deadline同拍commit在next中优先；直接CAL deadline输出tick248与commit同沿冲突属既有事项，保持关联，不重编号。reset清全state，宽度/计数依赖默认合法参数，非法参数完整拒绝范围尚需同类汇总。门禁AST结构成功不等于行为合同成功。\n\nAMB recheck RTL374行/TB655行代码已读，C16周期章节及PWI实际连线已读：其本地sample_inflight只有accepted/stage/lifecycle释放，没有deadline输入。正在追踪AMI中间ready握手与外层deadline释放后的重试可达性，尚未把疑点定性为发现。\n''',encoding='utf-8')
rows=list(csv.DictReader((OUT/'coverage.csv').open(encoding='utf-8-sig')))
for r in rows:
 if 'SYSTEM_FAULT_ABORT_SUPERVISOR' in r['path']:
  r.update(status='部分' if r['check_item']=='版本依赖/ID/锚点' else '完成',contract_or_id='C24 §1-7 / SUP-01..10 / K02',evidence='报告批次1; supervisor仿真; 源码/合同全文',remaining='跨合同与系统级ID待闭合' if r['check_item']=='版本依赖/ID/锚点' else 'B-001/B-002记录')
 if '400hz_frame_calibration_scheduler' in r['path'] or '400HZ_FRAME_CALIBRATION_SCHEDULER' in r['path']:
  r.update(status='部分',contract_or_id='C08 / FSC / SID / LFA / OIB',evidence='报告批次2; scheduler_*仿真; RTL/TB/合同全文',remaining='系统链/完整ID映射/边界drain量化待审；已确认B-003..005')
 if 'amb_recheck_scheduler' in r['path']:
  r.update(status='部分',contract_or_id='C16 §9 / AMR',evidence='RTL/TB全部执行代码; PWI980-1029',remaining='全文注释/合同余章、deadline重试与系统证据待审')
with (OUT/'coverage.csv').open('w',encoding='utf-8-sig',newline='') as fp:
 w=csv.DictWriter(fp,fieldnames=rows[0].keys());w.writeheader();w.writerows(rows)
(OUT/'handoff.md').write_text(f'''# B 交接 — 批次2完成，继续审阅\n\n固定提交：{COMMIT}\n报告：{OUT/'PPG_REVIEW_B.md'}\n覆盖：{OUT/'coverage.csv'}\n协议表：{OUT/'protocol_table.md'}\n证据：{OUT/'evidence'}\n\nB-001 S3 watchdog非法参数未拒绝；B-002 S2 supervisor历史rearm覆盖；B-003 S1 NORMAL默认5001拍偏差；B-004 S2 scheduler TB允许5001并固定Q3；B-005 S1 CAL末拍overlay覆盖abort（物理新owner仍被阻止，不是永久死锁结论）。均有原RTL/负对照或相邻边界仿真，见报告。\n七RTL actual skill analyze/AST完成。全部29文件与固定commit字节一致。源码只读。supervisor全文审；scheduler全文功能正文已读、系统映射待闭合；AMB recheck执行代码全文已读，正追踪内部inflight遇外层deadline后的重试。其余AMI、SSW、PWI/PWC、9合同/6系统TB完整语义仍在进行。F-001～007保留关联。不得把当前部分覆盖当全部签核。\n''',encoding='utf-8')
print('batch2 saved')
