from review import *
p=OUT/'PPG_REVIEW_B.md'
p.write_text(p.read_text(encoding='utf-8')+'''\n## 批次4：独立分支资格和AMI历史诊断\n\n### B-008 — measurement先消费会把仍pending的detection样本资格清0\n\n- S1 / RTL。AMI:1231-1241只保存一个`result_sample_valid_o`，1238-1239在measurement transfer时清零；同一寄存器同时驱动measurement资格（1028）和PWI detection `i_sample_valid`（2518）。C10:535、691-694、941-946明确要求两分支独立保留，pending分支资格不能被另一分支消费改写。\n- 原文（2行）：`end else if(flag_measurement_transfer == 1'b1)begin`；`result_sample_valid_o <= 1'b0;`。\n- 复现：evidence/branch_qualification_v2完整复用原AMI TB现有N08之前的真实子模块路径与FIR背压窗口，47项原比较全PASS，随后measurement实际消费的下一拍，window=1/firbusy=1/detpending=1/measpending=0/samplequal=0，BWINDO PASS、BQUALI FAIL退出1。该NORMAL结果没有invalid注入，生产资格应为1。\n- 因果对照：evidence/branch_qualification_counterfactual_v2只在本组副本让1238的measurement清零还要求detection不pending；完全相同窗口samplequal=1，原47比较及两个扩展比较全部PASS（49/0）。这只是定位，不作为正式分支独立存储修复。第一版检查点位于measurement尚未消费的一拍，measpending=1，资格尚为1，两边BWINDO均FAIL，不作为缺陷证据。\n- 影响：PWI稍后握手会把一个成功NORMAL样本当invalid消耗，FIR不得把它计入历史/检测；正式measurement虽已成功消费，算法路径丢失其资格。反驳：数值载荷仍保持，问题不是payload覆盖；C_ENABLE_TEST_INJECTION=0，排除F-001/X及受控invalid；所用背压窗口就是原N08合法压力场景，没有force或伪内部ready。未声明所有默认物理400 Hz帧都会命中该窗口。原TB只检查N08 abort身份，AMI-12/13只构造measurement反压，不比较反向pending资格，故基线48 PASS不能证明分支独立。置信度：真实链+限定counterfactual。建议单独保存measurement/detection资格，并比较两种消费顺序；不修复。\n\n### B-009 — AMI新合法START清除历史protocol sticky\n\n- S1 / RTL。C10 §15.1:1153明确历史protocol sticky只有reset或本地无active blocking cause后的diag_clear可清，START/STOP不能清。AMI:1186-1187却把START与diag_clear并列。\n- 原文（2行）：`end else if(i_start_ack_event == 1'b1 || i_diag_clear_event == 1'b1)begin`；`integration_protocol_error_sticky_o <= 1'b0;`。\n- evidence/ami_sticky_start：真实MANUAL启动完成后提交非法frame11，BSTICK验证sticky=1、blocking=0、ADC无inflight；STOP、撤销RUN及drain后BDRAIN验证empty=1且历史仍1；generation改2、合法新START后sticky=0，BKEEPH FAIL退出1；显式diag_clear BDIAGC PASS。3 PASS/1 FAIL。所有驱动在negedge，未保留旧owner，新START的安全前提已经比较。\n- 影响：软件未清历史即被新RUN静默抹去；不同于PWC已经实现PWC-41保留sticky的已知修复，不能用PWC通过替AMI证明。建议新START只重建RUN上下文，保留历史sticky，并加AMI跨RUN测试；不修复。置信度：合同+仿真确认。\n\n### C10全文审阅及待反驳事项\n\nC10 1337行已全文读完。其规范自检表AMI-46..54与现有叶子TB的同名46/47用途不同：现TB46是measurement discard、47是detection discard，实际只有48比较（含N08），不得重标为当前注入/全合同54项。此项与F-003锚点/语义映射问题关联，不简单再创建一条重复“旧锚点”。\n\n还需独立汇总的静态不一致：C10称注册AMI聚合/事件/每lane原子fault快照，而实际多项直接组合来自live子模块；CHARACTERIZATION在normal fork之后才gate tracking valid，内部raw tracking pending仍会建立（违背§8.5第7项），但IDAC消费口被禁止，尚无实际自动调码错误证据。取消期间注入ready与diag_clear本地active门控也需与Top受保护输入前提逐项核对，当前不提升未证实风险为S1。\n''',encoding='utf-8')
rows=list(csv.DictReader((OUT/'coverage.csv').open(encoding='utf-8-sig')))
for r in rows:
 if 'ADC_MEASUREMENT_AND_IDAC_INTEGRATION' in r['path']:
  r.update(status='部分',evidence='C10全文1337行; 报告批次3/4; 各短对照',remaining='依赖版本/全部矩阵ID、Top真实父链/系统覆盖、注册与fault snapshot等静态差异待汇总')
 if 'adc_measurement_idac_integration' in r['path']:
  r.update(status='部分',evidence='RTL/TB全部执行代码; evidence/skill; 报告批次3/4; 原TB48比较+扩展',remaining='注释全文与Top/系统对照、fault lane快照/active guard等剩余反驳；B-006..009已记录')
with (OUT/'coverage.csv').open('w',encoding='utf-8-sig',newline='') as fp:
 w=csv.DictWriter(fp,fieldnames=rows[0].keys());w.writeheader();w.writerows(rows)
(OUT/'handoff.md').write_text((OUT/'handoff.md').read_text(encoding='utf-8').replace('批次3完成','批次4完成')+'''\n更新：B-008 S1 measurement消费清共享sample-valid、破坏pending detection资格（原47比较通过而扩展捕获，限定counterfactual49/0）；B-009 S1 AMI START清历史sticky（合法drain/新generation对照3 PASS/1 FAIL）。C10全文1337行已读完。当前新发现B-001..009，仍不宣称29文件完成。继续PWI599-979/PWC/SSW及余合同/系统TB。\n''',encoding='utf-8')
print('batch4 saved')
