from review import *
p=OUT/'PPG_REVIEW_B.md'
p.write_text(p.read_text(encoding='utf-8')+'''\n## 批次5：精度取消优先级与PWI尾部测试\n\n### B-010 — PWC discard与安全边界同拍仍提交精度和正常事件\n\n- S1 / RTL。PWC:264-265的enter/return commit未排除当前generation discard，虽然602-603的FSM优先回IDLE、337-348窗口资格优先清0，316-334精度寄存器及355-397事件仍按commit更新。C23:213-228、475-476、703-710、779-784要求discard高于提交，不改物理精度、不发fine start/15-to-9。\n- 原文（2行）：`assign flag_enter_commit = (state_current == ST_WAIT_ENTER) && i_frame_safe_boundary && i_precision_takeover_safe && i_analog_safe && !i_recheck_busy;`；`assign flag_return_commit = (state_current == ST_WAIT_RETURN) && i_frame_safe_boundary && i_precision_takeover_safe && i_analog_safe;`。\n- evidence/pwc_cancel_commit：复用叶子TB真实请求与ready/valid，当前generation的STOP/abort/system-fault分别与合格安全边界同拍，enter后三种均mode=1/window=0/start=1/state=IDLE，return后三种均mode=0/window=0/return=1/state=IDLE，6项FAIL；6项setup、旧generation仍允许正常提交与正常返回共8项PASS，退出1。全部刺激在negedge或posedge后#1，未force。evidence/pwc_cancel_commit_counterfactual仅在本组副本对两个commit条件加!flag_lifecycle_cancel，相同14比较全PASS。副本仅定位，不是共享RTL修复。\n- 影响：正常提交事件出现在被撤销generation，物理committed值与已清窗口/FSM不一致。父链AMI:962复合安全公式未屏蔽terminal action，:970检测discard可以由pending PWC触发；:2539原样宏帧边界、:2541安全资格进入PWI。完整Top同拍触发尚未模拟，不能夸大成必然新ADC启动或永久死锁；模块直接合同已被可达合法端口组合反证。建议所有提交/事件/计数以同一有效终端优先级门控，补双方向同拍测试；置信度：短仿真+限定counterfactual确认。\n\n### B-011 — PWI-01丢弃累计前置检查，提前尾部错误也PASS\n\n- S2 / TB。PWI TB:736/738/743累计pending、真实fine事件数、前10笔旧精度不报错到flag_case_ok，但:746最终判定没有该变量；PWI-02:758-766累计值在:769同样遗漏。C18:639要求前10笔合法、第11笔才错误，不能只比较第11笔已有sticky。\n- 原文（1行）：`check_case("PWI-01", o_peak_valley_protocol_error_sticky && (cnt_fine_start_event == 1) && o_active_precision_mode && o_fine_window_active);`。\n- evidence/pwi_tail_original_check与pwi_tail_early_overflow_mutant：只跑真实链原TB第一项到:746；本组负对照将C-owned峰谷检测器的FIR_GROUP_DELAY_LIMIT从参数10改0，使第一笔旧9-bit中心样本就报overflow，原比较两边仍各1 PASS/0 FAIL，退出0。不是请求修复C源码，也不证明原峰谷RTL错。\n- 进一步核验：原累计flag_case_ok在两边均0；只把它加入最终比较会连原RTL也FAIL，原因是:738在fine pulse的下一个posedge计数器尚未计数时读count（pulse_safe_boundary在commit后的negedge就返回）。evidence/pwi_tail_sampled_strict在该观察点补一个negedge、将累计值用于最终比较：原RTL B_FINE_COUNTER=1、B_TAIL10 sticky=0/saved=1，PASS；evidence/pwi_tail_sampled_strict_early_mutant在同样观察点sticky=1/saved=1，最终FAIL退出1。首轮strict失败只定位TB采样问题，不当RTL缺陷。\n- 建议同时修复事件计数采样窗口与累计前置条件使用；退出尾部项亦使用已累计比较；补每个真实owner条件独立阻止recheck接管。置信度：真实链负对照。PWI TB仅5条历史项，sample_valid绑1/discard绑0，C18:690已承认06..10缺独立TB；不重复为“新遗漏”。\n\n### 本批语义审阅\n\nPWC RTL全部执行代码、文件头以及TB全部执行代码，C23全文1029行已读；PWI RTL全部执行代码/文件头、TB全部执行代码和C18全文690行已读。C18:201把fine/reacquire限制的消费者写成PWC，但实际两项接PVW（PWC无这两个输入）；C18新V2.1补记仍同时把V2.0称唯一current，C23/C16依赖称C18 V2.1。此类合同内部消费者/版本冲突待在全合同对照中聚合，与F-003旧锚点区分。\n\nSSW RTL1519行全部执行代码、C09全文918行已读，TB目前1-470；新待反驳：SSW:514-517 abort优先保持owner会吞同拍匹配完成，而AMI完成是单周期注册旁带。尚未做short reproducer，不记为确认发现。cause22按D03冻结不适用，未重复列缺陷。\n''',encoding='utf-8')
rows=list(csv.DictReader((OUT/'coverage.csv').open(encoding='utf-8-sig')))
for r in rows:
 if any(x in r['path'] for x in ['precision_window_controller','PRECISION_WINDOW_CONTROLLER','precision_window_integration','PRECISION_WINDOW_INTEGRATION']):
  r.update(status='部分',evidence='全文执行代码/文件头与C18/C23全文; 批次5; 两组短对照',remaining='系统TB及跨合同ID/消费者/版本逐项对照、注释合同关联收尾；B-010/011已记录')
 if any(x in r['path'] for x in ['sar9_sar15_safe_selection','SAR9_SAR15_SAFE']):
  r.update(status='部分',evidence='RTL全部执行代码; C09全文; TB1-470; 门禁旧证据',remaining='TB471-1116/注释、同拍abort完成、Top/跨合同对照')
with (OUT/'coverage.csv').open('w',encoding='utf-8-sig',newline='') as fp:
 w=csv.DictWriter(fp,fieldnames=rows[0].keys());w.writeheader();w.writerows(rows)
(OUT/'protocol_table.md').write_text((OUT/'protocol_table.md').read_text(encoding='utf-8')+'''\n| PWC matching-generation discard + safe-boundary | FSM clears to IDLE and fine qualification=0, but original enter/return commit still changes physical precision and emits normal event | B-010: six direction/reason cases fail; stale generation control passes; commit-gate counterfactual14/0 |\n| PWI entry-tail TB | Original final check does not use accumulated first10 legality; registered event counter sampled before next increment | B-011: early overflow mutant escapes; corrected observation + cumulative check differentiates original/negative |\n''',encoding='utf-8')
(OUT/'handoff.md').write_text(f'''# B交接 — 批次5完成，审阅持续\n\n固定提交：{COMMIT}\n报告：{p}\n覆盖：{OUT/'coverage.csv'}\n协议表：{OUT/'protocol_table.md'}\n证据：{OUT/'evidence'}\n\n已确认B-001..011：1 S3参数拒绝；2 S2 supervisor rearm测试；3 S1 NORMAL5001拍；4 S2 scheduler周期/Q3测试；5 S1 CAL rollover覆盖abort；6 S1 AMI formal-discard身份取错fork；7 S1 periodic deadline仅清外层inflight、锁死重试；8 S1 shared sample资格被measurement消费清除；9 S1 AMI START清历史sticky；10 S1 PWC discard+commit同拍仍提交/事件；11 S2 PWI尾部测试丢弃累计判定。所有新增均有短对照，详报告和独立证据目录。\n\nC08/C10/C16/C18/C23/C24全文已读；七RTL除注释收尾外执行代码全读（SSW刚完成）；单位TB剩SSW471-1116及部分文件头；6系统TB、checklist和ADC_IDAC_SPEC全文尚待审，依赖/ID/所有权父链尚未签核，29文件仍不可声称完成。下一步SSW同拍abort+completion反驳以及剩余TB/合同。SSW cause22按D03不适用。\n\n反驳边界：人为保持RUN=1取消recheck可占用，但真实Top STOPPING撤销RUN会清理，未当Top永久死锁。B-010未声称完整Top同拍已模拟。A负责长全回归；本组未重复长套件。共享源只读，本组副本/输出在上述目录或独立Linux /tmp；F-001..007继续关联。\n''',encoding='utf-8')
print('batch5 saved')
