from review import *
p=OUT/'PPG_REVIEW_B.md'
p.write_text(p.read_text(encoding='utf-8')+'''\n## 批次1：环境、scheduler协议骨架及supervisor\n\n任务分类 analyze + validate。实际调用skill `analyze_existing_verilog`、formatter AST；七个RTL均ast_ok=true，产物在evidence/skill。原同版本strict门禁及独立lint逐文件复用，仿真与门禁分别解释。未调用verify/repair、未应用修复。主责29文件均与git show字节相等。\n\n### B-001 — watchdog非法参数未按合同在elaboration拒绝\n\n- S3 / 合同·RTL一致性。位置：C24合同第1节（43行）明确 `Elaboration shall reject ... COUNTER_WIDTH < $clog2(CYCLES + 1)`；RTL参数54-55行与191-192、433-450行无参数检查。\n- 关键原文（2行）：`parameter integer C_ADC_DRAIN_WATCHDOG_COUNTER_WIDTH = 32'd13`；`flag_watchdog_timeout_fire = flag_watchdog_window_active && (cnt_adc_drain_watchdog == (C_ADC_DRAIN_WATCHDOG_CYCLES - 1))`。\n- 实际证据：evidence/supervisor_invalid_width/compile.log与result.json，原模块TB仅把C_WD_WIDTH从4改1，C_WD_CYCLES仍8；Icarus 11.0 -g2012 -Wall编译rc=0，运行SUP06B FAIL（其余13 PASS）。不能达到7的1-bit计数器循环0/1，无超时故障。默认合法参数不受此结论影响。\n- 反驳：Top默认5000/13合法、manager没有可变watchdog配置，故不扩大为默认芯片S1；所有共享RTL搜索未找到参数拒绝补偿，源为独立模块并承诺elaboration拒绝；不是已知风格或D03事项。置信度：仿真确认非法值接受，静态确认无guard。建议：由owner决定增加合法参数门禁或修改参数使用前提；不提供/应用修复。\n\n### B-002 — SUP10A不能证明保留历史时episode重新开启，错误实现逃过原TB\n\n- S2 / TB。位置：rtl/ppg_system_fault_abort_supervisor/tb_ppg_system_fault_abort_supervisor.v:475-488。关键原文（3行）：\n```text\n// SUP-10：验证第二个独立episode（此前episode均已完整关闭+诊断清除，非同一episode延续）依然\n// 完整触发abort/STOP/丢弃三事件并锁存全新快照——这是K02"episode开合独立于首故障快照历史，\ncheck_case("SUP10A", (o_system_fault_blocking === 1'b1) &&\n```\n- 依据：C24第4节规定第二个独立故障在旧first-fault未diag_clear时仍发新trio且不覆盖旧snapshot；该TB在365-368、414-416、459-461清历史，SUP10A反而期待全新cause03。它验证了清历史后的新episode，没有构造历史仍valid的关键前提。\n- 证据：evidence/supervisor_original/run.log真实14 PASS。仅把RTL第198行 `flag_new_any && !system_fault_blocking_o` 变成 `flag_new_any && !system_fault_cause_valid_o`（本组副本），evidence/supervisor_original_rearm_mutant仍14 PASS。补充TB保留cause01历史、等blocking关闭再发送cause02，evidence/supervisor_extended原RTL 6比较/0失败；同变异evidence/supervisor_extended_rearm_mutant BREARM FAIL、退出1。错误期望负对照evidence/supervisor_wrong_expected_negative也报SUP01A FAIL；原TB失败虽退出0，必须读取FAIL/计数。\n- 反驳：本条不宣称原RTL错误；第198行原实现正确。系统级其他TB/K02证据仍须核对，不能从本条推断全系统完全没覆盖；本文件新增声明本身过强。不是F-001悬空输入问题。建议补保留历史的rearm比较并要求trio和旧snapshot同时成立；不修复。\n\n### supervisor已核对及限制\n\n已全文读取RTL465行、TB511行与合同161行。reset覆盖全部寄存器；三路记录与watchdog快照优先级正确，identity_valid=0时所有身份字段归零；summary仅bit0..8，reserved位保持0；历史不被episode-close清除。无组合反馈、无ready/完成/owner释放输出。真实idle在计数/触发同拍优先，6比较补充场景验证阈值前一拍无故障和阈值同拍idle阻止超时。合法clear只在episode关闭后，new fault胜过同拍clear。外部响应假设：本地active由各owner真实恢复，watchdog永不伪造idle或DONE。参数非法reject缺失已报B-001。SUP05/08/10 AMI延迟discard/Top merge不由这个叶子TB闭合。\n\n''',encoding='utf-8')
rows=list(csv.DictReader((OUT/'coverage.csv').open(encoding='utf-8-sig')))
for r in rows:
 if 'system_fault_abort_supervisor' in r['path']:
  r.update(status='完成' if r['check_item'] not in ['版本依赖/ID/锚点'] else '部分',contract_or_id='C24 §1-7 / SUP-01..10 / K02',evidence='PPG_REVIEW_B.md批次1; evidence/supervisor_*; evidence/skill',remaining='跨合同版本/系统SUP05/08/10来源及全ID锚点待汇总' if r['check_item']=='版本依赖/ID/锚点' else '原RTL无修复；B-001/B-002已报告')
 if 'ppg_400hz_frame_calibration_scheduler/ppg_' in r['path']:
  r.update(status='部分',contract_or_id='C08 §8-10 / SID-05 / LFA / OIB',evidence='源码63-884行已读; evidence/skill',remaining='合同后半、模块TB全文、最小边界/rollover反驳未完成')
with (OUT/'coverage.csv').open('w',encoding='utf-8-sig',newline='') as fp:
 w=csv.DictWriter(fp,fieldnames=rows[0].keys());w.writeheader();w.writerows(rows)
(OUT/'protocol_table.md').write_text('''# 请求→身份保持→提交/截止→完成/discard→owner释放（逐拍草表）\n\n固定commit d18c6954621e53e5a6505dd3a6c688c266d23839。边沿t使用沿前值，t+1表示寄存结果。静态与仿真分开。\n\n| 阶段 | 沿t资格/行为 | 沿t+1保持/释放 | 取消及边界 | 证据 |\n|---|---|---|---|---|\n| AMI校准请求 | valid & scheduler ready，全载荷NORMAL_PPG/PHOTODIODE/SAR9合法 | Scheduler CAL_REQ_PENDING=1，AMI calibration_request_inflight=1 | STOP/abort/block取消；迟到波形要重试 | Scheduler426-433,650-655; AMI1791-1800 |\n| waveform | 仅NORMAL RED tick0、IR160、CAL local0，SSW ready独立 | 槽有效，pending；冻结码与epoch。sample_index不动 | 错过固定点不迟到fire；STOP可继续被动tick自然收尾 | Scheduler437-445,657-690 |\n| owner commit | 最早pending CAL>RED>IR，SSW owner_ready & AMI ready & allow & lifecycle | 唯一inflight锁存sample/type/color/generation，next_sample加1 | STOP/abort同拍gate禁止新提交 | Scheduler447-456,692-709 |\n| owner截止 | pending且无inflight达到283/443/248 | 未fire则pending清、soft sticky置1，不fabricate完成 | 同拍commit优先于本地timeout；CAL输出却直接未mask条件，known tick248 | Scheduler465-467,567,736-750 |\n| DONE | 匹配sample与generation释放；success额外要求Q3闭合 | 无论success仍清inflight；成功NORMAL只置相应done | 旧/错/重复DONE不释放新owner，错配触发阻断 | Scheduler459-460,711-735 |\n| STOP/abort | 禁新owner；已owner标discard，STOP保留tick，abort清frame | 真实DONE后释放，等待SSW安全、物理idle及数字空 | 外部ADC永不DONE/idle不能当作内部死锁 | Scheduler597-619,559 |\n| supervisor | 注册本地fault或drain watchdog触发 | episode opening恰好一次abort/stop/discard trio | close独立first-fault历史；clear不能release owner | C24§4-6; supervisor198-205,253-294; extended实测 |\n\n待补：AMI完成流水/输出分叉释放、SSW完整owner身份/Q3、PWC/PWI mode切换、AMB recheck请求。当前不是完整协议签核。\n''',encoding='utf-8')
(OUT/'handoff.md').write_text(f'''# B 交接 — 批次1完成\n\n固定提交：{COMMIT}\n输出目录：{OUT}\n报告：{OUT/'PPG_REVIEW_B.md'}\n覆盖：{OUT/'coverage.csv'}\n协议表：{OUT/'protocol_table.md'}\n证据：{OUT/'evidence'}\n\n新发现：B-001 S3非法watchdog参数未拒绝，B-002 S2 supervisor保留历史时episode rearm覆盖缺口（变异逃过14 PASS，扩展场景捕获）。原RTL扩展6比较0失败。\n已有F-001～007保留；已实读F-001正负A/B输出并关联四个本组TB，未重复编号。\n七RTL实际skill analyze/formatter AST通过结构解析、复用门禁存于evidence/skill；29主责文件字节一致。\n当前已全文审supervisor RTL/TB/合同，跨合同版本/系统级ID仍部分。scheduler RTL已读、协议骨架建立；其余主责尚未完成。继续scheduler合同/TB及AMI、SSW、PWC/PWI和recheck。共享源码未改。\n''',encoding='utf-8')
print('batch1 saved')
