from review import *
p=OUT/'PPG_REVIEW_B.md'
p.write_text(p.read_text(encoding='utf-8')+'''\n## 批次6：完成与abort同拍、SSW恢复链\n\n### B-012 — SSW abort优先保持吞掉匹配完成，重启仍不能建立新owner\n\n- S1 / RTL，置信度：叶子四组合、顶层真实ADC路径及限定counterfactual确认。SSW:427已识别匹配sample_index和generation；:514-515的abort保持分支优先于:516-517释放，吞掉无ready单周期完成。C09:346-354、678-689与连接检查表:225-238要求匹配完成success=0/1均释放物理owner；取消只应阻止后续数据/模拟行为，不得遗失已经到达的释放事实。\n- 原文（3行）：`end else if(i_control_abort_event == 1'b1)begin` / `adc_owner_inflight_o <= adc_owner_inflight_o;` / `end else if(flag_owner_release == 1'b1)begin`。该寄存器:511-520仅reset、release、commit改变；diag_clear、START、物理idle均不清owner。\n- evidence/ssw_abort_done：真实waveform/owner握手，SAR9/SAR15×success0/1共四组合，同拍前flag_owner_release=1，沿后owner=1/idle=0，撤销完成脉冲后20拍仍占用，共8比较FAIL。迟一拍匹配失败完成与同拍错ID后迟到正确完成两个对照PASS；abort时模拟输出关闭。evidence/ssw_abort_done_counterfactual只删除独立副本的abort保持分支，两条原行，释放获得优先级，六项case全PASS。\n- evidence/top_abort_done_v3：复用lifecycle TB合法MANUAL双光配置、真实Q3和CLK_DOUT/RAW任务，生产注入参数0，未force。AMI:912/1199-1202正常完成为注册单周期；Top:353-357原始abort同样注册。因此在AMI emit前一个negedge拉原始abort，下一消费沿真实pair=abort1/completion1/release1。沿后Scheduler owner=0、AMI owner=0、SSW owner=1；ADC最终physicalidle=1、waveidle=1、AMIempty=1，SSWidle=0。\n- 必须限定：首次生命周期在3拍进入CONFIG，并未卡在STOPPING；Top:741-744的排空资格使用physicalidle/AMIempty/IDACidle/analog-safe，未用SSW完整idle。之后100拍、diag_clear、合法重新COMMIT/START仍留SSW owner。新RUN 7000拍newowners=0，自动故障cause=21并再次回CONFIG；这是已完成旧owner的内部残留阻断恢复，不是ADC不响应。generation已改变，即使新completion也不能按旧generation释放该owner。叶子寄存器缺复位外恢复路径，正常外部接口无法补发已消费DONE。\n- evidence/top_abort_done_v3_counterfactual：相同全链短序列，旧owner按匹配完成释放；重启5拍newowners=1、lifecycle=RUN、blocking=0/cause00，PASS。新owner之后等待外部ADC属于正常外部等待，未把该在途事务误当内部死锁。原v1已证失释放；v2尝试START清理被真实反证，v3完整记录恢复失败因果。全部独立复制，未改共享源，未重复A全回归。\n- 建议：匹配完成事实优先释放物理owner，同时取消仍优先清波形/结果资格；统一owner相关sticky在相同生命周期清理。补四precision/success组合及顶层注册abort与完成同拍、重启恢复验证。现有SSW迟到/错ID测试和LFA-04先abort后DONE未覆盖此竞争。\n\n### 合同全文新增核对\n\n连接检查表430行和ADC_IDAC集成SPEC494行已全文读。检查表§15明确前文是2026-08-17设计快照、老联合TB退役、C01/C08/C09/C10权威且自身non-normative，因此不把前文旧版本/未实现状态另列当前缺陷。SPEC虽然文件头仍称“当前活动”，C10/矩阵把其定为non-normative设计参考；旧“待实现”校准/IDAC段不能推翻当前实现合同，保留为历史状态提醒，不报RTL缺功能。公共位宽/编码、握手单向依赖、物理idle/DONE区别与真实父链相符；当前generation字段以各模块新合同为准。\n\nSSW TB全部执行代码1116行已审，文件头注释仍需收尾。其同拍优先级问题已经闭合证据；C09 cause22仍按D03冻结不适用。六系统TB、跨合同矩阵ID/消费者/版本核对尚未完成，主任务继续。\n''',encoding='utf-8')
rows=list(csv.DictReader((OUT/'coverage.csv').open(encoding='utf-8-sig')))
for r in rows:
 if any(x in r['path'] for x in ['sar9_sar15_safe_selection','SAR9_SAR15_SAFE']):
  r.update(status='部分',evidence='RTL/TB全部执行代码; C09全文; B-012叶子/真实Top及counterfactual',remaining='注释/矩阵ID/系统TB对照收尾；B-012确认内部恢复受阻，首次CONFIG可达')
 if any(x in r['path'] for x in ['PORT_CONNECTION_CHECKLIST','ADC_IDAC_INTEGRATION_SPEC']):
  r.update(status='部分',evidence='全文逐项；批次6；历史non-normative边界已确认',remaining='依赖/ID引用实际矩阵全面对照')
 if 'tb_ppg_control_top_lifecycle_fault_adc_anomaly.v' in r['path']:
  r.update(status='部分',evidence='执行代码1-1237；真实Top短序列；批次6',remaining='1238-2172全文/文件头注释；矩阵ID与各比较对照')
with (OUT/'coverage.csv').open('w',encoding='utf-8-sig',newline='') as fp:
 w=csv.DictWriter(fp,fieldnames=rows[0].keys());w.writeheader();w.writerows(rows)
(OUT/'protocol_table.md').write_text((OUT/'protocol_table.md').read_text(encoding='utf-8')+'''\n| SSW abort + matching registered completion | abort hold overrides recognized release; real AMI/Scheduler release while SSW owner persists | B-012 four precision/success cases; six-case counterfactual; real Top old owner persists across diag clear/restart and new RUN fails, not first STOPPING deadlock |\n| Top lifecycle idle vs SSW complete idle | CONFIG can be reached with physical ADC/AMI/analog-safe idle despite SSW owner=1 | B-012 real Top: CONFIG3 cycles, SSWidle0; restart7000 cycles newowners0/cause21, counterfactual5 cycles newowner1 |\n''',encoding='utf-8')
(OUT/'handoff.md').write_text((OUT/'handoff.md').read_text(encoding='utf-8')+'''\n批次6补记：B-012确认SSW abort同拍吞匹配完成。叶子4precision/success组合失败，迟到/错ID对照PASS；仅删除副本abort保持分支6casePASS。真实Top生产注入0，AMI/Scheduler释放SSW残留；首次CONFIG可达，不能说STOPPING卡死。100拍/diagclear/重新START仍占用，重启7000拍newowners0/cause21；副本5拍新owner1。这是内部恢复受阻而不是外部未回应。全部证据evidence/ssw_abort_done*和top_abort_done_v3*；当前B-001..012。SSW TB全部执行代码已读，两个参考合同全文完成；六系统TB与矩阵/注释收尾继续。\n''',encoding='utf-8')
print('batch6 saved')
