`timescale 1ns/1ps
module audit_fir_ab;
reg clk=0;
reg rstn=1;
reg valid=0;
always #5 clk=~clk;
ppg_coarse_detection_fir #(.C_ENABLE_TEST_INJECTION(1)) a (
.i_clk(clk),
.i_rstn(rstn),
.i_run_enable(1'b1),
.i_start_ack_event('0),
.i_recheck_accept_event('0),
.i_recheck_busy('0),
.i_detection_discard_event('0),
.i_detection_discard_reason('0),
.i_detection_discard_identity_valid('0),
.i_detection_discard_sample_valid('0),
.i_detection_discard_frame_id('0),
.i_detection_discard_sample_index('0),
.i_detection_discard_color_ir('0),
.i_detection_discard_frame_type('0),
.i_detection_discard_precision('0),
.i_detection_discard_config_epoch('0),
.i_detection_discard_coef_epoch('0),
.i_detection_discard_dc_recovery_epoch('0),
.i_detection_discard_amb_code_epoch('0),
.i_detection_discard_dc_code_epoch('0),
.i_detection_discard_run_generation('0),
.i_run_generation('0),
.i_result_valid(valid),
.i_sample_valid(1'b1),
.i_coarse_ppg_value('0),
.i_coarse_valid(1'b1),
.i_coarse_recovery_calibrated(1'b1),
.i_stage1_saturation_low('0),
.i_stage1_saturation_high('0),
.i_coarse_saturation_low('0),
.i_coarse_saturation_high('0),
.i_config_epoch('0),
.i_coef_epoch('0),
.i_dc_recovery_coef_epoch('0),
.i_precision_mode('0),
.i_frame_id('0),
.i_sample_index('0),
.i_color_ir('0),
.i_frame_type(2'b10),
.i_amb_code_snapshot('0),
.i_dc_code_snapshot('0),
.i_amb_code_epoch('0),
.i_dc_code_epoch('0),
.i_test_inject_enable(1'b1),
.i_result_ready(1'b1)
);
ppg_coarse_detection_fir #(.C_ENABLE_TEST_INJECTION(1)) b (
.i_clk(clk),
.i_rstn(rstn),
.i_run_enable(1'b1),
.i_start_ack_event('0),
.i_recheck_accept_event('0),
.i_recheck_busy('0),
.i_detection_discard_event('0),
.i_detection_discard_reason('0),
.i_detection_discard_identity_valid('0),
.i_detection_discard_sample_valid('0),
.i_detection_discard_frame_id('0),
.i_detection_discard_sample_index('0),
.i_detection_discard_color_ir('0),
.i_detection_discard_frame_type('0),
.i_detection_discard_precision('0),
.i_detection_discard_config_epoch('0),
.i_detection_discard_coef_epoch('0),
.i_detection_discard_dc_recovery_epoch('0),
.i_detection_discard_amb_code_epoch('0),
.i_detection_discard_dc_code_epoch('0),
.i_detection_discard_run_generation('0),
.i_run_generation('0),
.i_result_valid(valid),
.i_sample_valid(1'b1),
.i_coarse_ppg_value('0),
.i_coarse_valid(1'b1),
.i_coarse_recovery_calibrated(1'b1),
.i_stage1_saturation_low('0),
.i_stage1_saturation_high('0),
.i_coarse_saturation_low('0),
.i_coarse_saturation_high('0),
.i_config_epoch('0),
.i_coef_epoch('0),
.i_dc_recovery_coef_epoch('0),
.i_precision_mode('0),
.i_frame_id('0),
.i_sample_index('0),
.i_color_ir('0),
.i_frame_type(2'b10),
.i_amb_code_snapshot('0),
.i_dc_code_snapshot('0),
.i_amb_code_epoch('0),
.i_dc_code_epoch('0),
.i_test_inject_enable(1'b1),
.i_test_calibration_loss_inject_valid(1'b0),
.i_result_ready(1'b1)
);
ppg_coarse_detection_fir #(.C_ENABLE_TEST_INJECTION(0)) c (
.i_clk(clk),
.i_rstn(rstn),
.i_run_enable(1'b1),
.i_start_ack_event('0),
.i_recheck_accept_event('0),
.i_recheck_busy('0),
.i_detection_discard_event('0),
.i_detection_discard_reason('0),
.i_detection_discard_identity_valid('0),
.i_detection_discard_sample_valid('0),
.i_detection_discard_frame_id('0),
.i_detection_discard_sample_index('0),
.i_detection_discard_color_ir('0),
.i_detection_discard_frame_type('0),
.i_detection_discard_precision('0),
.i_detection_discard_config_epoch('0),
.i_detection_discard_coef_epoch('0),
.i_detection_discard_dc_recovery_epoch('0),
.i_detection_discard_amb_code_epoch('0),
.i_detection_discard_dc_code_epoch('0),
.i_detection_discard_run_generation('0),
.i_run_generation('0),
.i_result_valid(valid),
.i_sample_valid(1'b1),
.i_coarse_ppg_value('0),
.i_coarse_valid(1'b1),
.i_coarse_recovery_calibrated(1'b1),
.i_stage1_saturation_low('0),
.i_stage1_saturation_high('0),
.i_coarse_saturation_low('0),
.i_coarse_saturation_high('0),
.i_config_epoch('0),
.i_coef_epoch('0),
.i_dc_recovery_coef_epoch('0),
.i_precision_mode('0),
.i_frame_id('0),
.i_sample_index('0),
.i_color_ir('0),
.i_frame_type(2'b10),
.i_amb_code_snapshot('0),
.i_dc_code_snapshot('0),
.i_amb_code_epoch('0),
.i_dc_code_epoch('0),
.i_test_inject_enable(1'b1),
.i_result_ready(1'b1)
);

integer guard;
initial begin
  #1 rstn=0;
  #20 rstn=1;
  @(negedge clk); valid=1;
  #1;
  $display("INPUT qualified A(open,enabled)=%b B(tie0,enabled)=%b C(open,disabled)=%b",a.flag_sample_qualified,b.flag_sample_qualified,c.flag_sample_qualified);
  guard=0;
  while (b.o_result_valid !== 1'b1 && guard<200) begin @(posedge clk); #1; guard=guard+1; end
  $display("OUTPUT valid A=%b B=%b C=%b qualified A=%b B=%b C=%b guard=%0d",a.o_result_valid,b.o_result_valid,c.o_result_valid,a.o_detection_qualified,b.o_detection_qualified,c.o_detection_qualified,guard);
  if (guard>=200 || a.o_detection_qualified !== 1'bx || b.o_detection_qualified !== 1'b0 || c.o_detection_qualified !== 1'b1) $fatal(1,"AUDIT_AB_FAIL");
  $display("AUDIT_AB_CONFIRMED");
  $finish;
end
endmodule
