"""Generate / check the SHA-256 digests of the closure-matrix 26-file manifest (§12.4a).

Usage:
    python manifest_digest.py [--repo DIR] [--rev REV] [--matrix PATH]          # check
    python manifest_digest.py [--repo DIR] --write                              # regenerate

Rows: every `| Cnn |` / `| M01 |` row of the "12.4a ... Baseline Manifest" table.
Each row's path (`ppg_system_integration/X.md`, `ppg_system_config_manager/X.md`, ...
paths of the original development tree) is mapped to `contracts/<basename>` in this
repository.

Digest rule (stated in §12.4a itself):
  * contract rows: SHA-256 of the full file;
  * M01 (the matrix): SHA-256 of the matrix after the 64-hex digest in the M01 row
    is replaced by the literal `<SELF_SHA256>` (self-normalized).
Bytes are taken as stored in git (LF line endings): with --rev from `git show`,
otherwise from the working tree with CRLF normalised to LF, so that a CRLF
checkout (core.autocrlf=true) gives the same digest as the committed blob.

Check mode prints one line per row (MATCH / MISMATCH / MISSING) and exits 1 when
any row does not match. --write rewrites the SHA-256 cell of every row to
"`<digest>` (generated by tools/b_merge_tools/manifest_digest.py)" and writes the
M01 digest last; it never touches any other cell. Run it only after every other
contract, matrix and alias-table change of a batch.
"""
import argparse
import hashlib
import os
import re
import subprocess
import sys

ROW = re.compile(r'^\| (C\d\d|M01) \| `([^`]+)` \|')
HEX = re.compile(r'`([0-9a-f]{64})`')
SELF = '<SELF_SHA256>'
TABLE_START = '#### 12.4a'
NOTE = ' (generated by tools/b_merge_tools/manifest_digest.py)'


def read_bytes(repo, rel, rev):
    if rev:
        out = subprocess.run(['git', '-C', repo, 'show', '%s:%s' % (rev, rel)], capture_output=True)
        return out.stdout if out.returncode == 0 else None
    path = os.path.join(repo, rel)
    if not os.path.exists(path):
        return None
    return open(path, 'rb').read().replace(b'\r\n', b'\n')


def table_rows(text):
    """Yield (line_index, id, mapped_rel_path, sha_cell_index) for the manifest table."""
    lines = text.split('\n')
    start = next(i for i, l in enumerate(lines) if l.startswith(TABLE_START))
    rows = []
    for i in range(start + 1, len(lines)):
        l = lines[i]
        if l.startswith('#'):
            break
        m = ROW.match(l)
        if m:
            rows.append((i, m.group(1), 'contracts/' + os.path.basename(m.group(2))))
    return lines, rows


def sha_cell(line):
    """Index of the SHA-256 cell (8th column) in a manifest row."""
    cells = line.split(' | ')
    return cells, 7


def self_normalized(matrix_text, m01_index):
    lines = matrix_text.split('\n')
    lines[m01_index] = HEX.sub('`' + SELF + '`', lines[m01_index], count=1)
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--repo', default=os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
    ap.add_argument('--rev')
    ap.add_argument('--matrix', default='contracts/PPG_CONTRACT_CLOSURE_MATRIX.md')
    ap.add_argument('--write', action='store_true')
    args = ap.parse_args()
    if args.write and args.rev:
        ap.error('--write works on the working tree only')

    raw = read_bytes(args.repo, args.matrix, args.rev)
    text = raw.decode('utf-8')
    lines, rows = table_rows(text)
    results = []
    for idx, rid, rel in rows:
        if rid == 'M01':
            continue
        data = read_bytes(args.repo, rel, args.rev)
        recorded = HEX.search(lines[idx])
        if data is None:
            results.append((rid, rel, 'MISSING', None, recorded and recorded.group(1)))
            continue
        digest = hashlib.sha256(data).hexdigest()
        results.append((rid, rel, None, digest, recorded and recorded.group(1)))

    if args.write:
        for (rid, rel, state, digest, _), (idx, _, _) in zip(results, [r for r in rows if r[1] != 'M01']):
            if state == 'MISSING':
                print('cannot write: %s %s missing' % (rid, rel))
                return 1
            cells, k = sha_cell(lines[idx])
            cells[k] = '`%s`%s' % (digest, NOTE)
            lines[idx] = ' | '.join(cells)
        m01 = next(r for r in rows if r[1] == 'M01')
        cells, k = sha_cell(lines[m01[0]])
        cells[k] = '`%s`%s' % ('0' * 64, NOTE)
        lines[m01[0]] = ' | '.join(cells)
        normalized = self_normalized('\n'.join(lines), m01[0])
        m01_digest = hashlib.sha256(normalized.encode('utf-8')).hexdigest()
        lines[m01[0]] = lines[m01[0]].replace('0' * 64, m01_digest, 1)
        out = '\n'.join(lines)
        open(os.path.join(args.repo, args.matrix), 'w', encoding='utf-8', newline='\n').write(out)
        print('written: %d contract rows + M01 %s' % (len(results), m01_digest))
        return 0

    m01 = next(r for r in rows if r[1] == 'M01')
    rec = HEX.search(lines[m01[0]])
    m01_digest = hashlib.sha256(self_normalized(text, m01[0]).encode('utf-8')).hexdigest()
    results.append(('M01', args.matrix, None, m01_digest, rec and rec.group(1)))
    bad = 0
    for rid, rel, state, digest, recorded in results:
        if state is None:
            state = 'MATCH' if digest == recorded else 'MISMATCH'
        bad += state != 'MATCH'
        print('%-8s %s %s recorded=%s computed=%s' % (state, rid, rel, (recorded or '-')[:12], (digest or '-')[:12]))
    print('rows %d, match %d, mismatch/missing %d' % (len(results), len(results) - bad, bad))
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main())
