from pathlib import Path
import csv,json,re,collections,datetime
from source_groups_inspect_A import scope,token,active_source
B=Path(__file__).resolve().parent;S=B/'snapshot';E=B/'evidence';O=E/'global_closure_20261004'
ml=(S/'contracts/PPG_CONTRACT_CLOSURE_MATRIX.md').read_text(encoding='utf-8').splitlines()
inventory=list(csv.DictReader((O/'ledger_port_inventory.csv').read_text(encoding='utf-8-sig').splitlines()))
byline={int(r['line']):r for r in inventory}
cache={p.name:p.read_text(encoding='utf-8').splitlines() for p in (S/'contracts').glob('*.md')}
# This is a manual adjudication register, not a new Verilog parser. The module
# and declaration inventory comes from the repo's canonical Erie AST facade.
# Every ambiguous Source group below has an explicit human-selected rationale.
groups={
 'C01':{
  208:'V4 source snapshot/update group; current C03 joint mailbox ports and Top boundary already checked.',
  210:'Synchronized START/STOP/clear/abort event group, not a demand for literal spelling.',
  211:'Physical RAW/CLK_DOUT group, four actual AMI inputs; current C10 6.4 names each member.',
  212:'Formal measurement consumer ready; actual AMI held result interface and C10 6.7.',
  213:'Verification injection category. Saturation pair is an explicitly self-recorded C01 gap in matrix 1512/1544 and explicitly normative C17:3; calibration-loss added in current C01:213/271/272. No missing hardware claim.',
  219:'All analog controls and 2 MHz passthrough, with named authoritative SSW C09 7.7 table and Top165-port independent audit.',
  221:'Production measurement/status/epoch/diagnostic output category. Actual origins in C02/C07/C08/C09/C10 verified; not an invented payload or extra producer.',
  290:'Explicit measurement discard full TXN_ID group. Existing F008 records the five missing formal epoch fields; do not duplicate.',
  291:'Explicit detection discard full TXN_ID group. Existing F008 retained.',
 },
 'C10':{
  537:'Current complete ACTIVE IDAC mode/enables/polarities/manual-min-max/threshold-confirm/recheck group. Actual C05 unpack slices and C17 definitions cross-checked.',
  579:'Current retained/injection/fault boundary; saturation verification pair explicitly added by current normative C17:3 and direct AMI/Top wiring. C01 already acknowledges its own omission.',
  559:'Current IDAC/precision/diagnostic table defines child registered source and declared widths; all listed subfields inherit current C17/C16/C18 definitions.',
  575:'Explicit PWI detector/recheck diagnostic group; AMI endpoint only and no implied Top consumer.',
  264:'ADC owner/context input group, including capture/redundancy context field aliases and committed precision. Exact private leaf declarations verified in canonical AST; reset/output completion exceptions separately ruled invalid.',
  821:'Explicit capture four fields and reverse ready link, start-fire context only; current capture/redundancy actual declarations and C11 2.1 boundary.',
  828:'Complete fixed S1 result into programmable S1 and router; held atomic payload plus metadata. Current C11/C12 field definitions support these private leaf port names.',
  833:'Router three mutually exclusive outputs share full payload, defined explicitly by C12; invalid frame_type excluded. No independent fault/owner creation.',
  850:'NORMAL fork two branches, router valid/ready belong to this actual boundary; C16 5.2/5.3 formal names.',
  965:'Calibration arbitration acceptance from genuine router/IDAC handshakes, current 11.4 accepted events and C12 corresponding ready.',
  633:'Protocol/owner fault arbitration current 6.11; the exact protocol sticky output is separately explicit in current 6.9 table:576. Group source is relevant, not a new missing formal port.',
 },
 'C13':{
  83:'Lifecycle generation/discard full TXN_ID expansion; common clock/reset boundary cross C13:116/124. F002 incomplete TXN_ID definition remains separately reported.',
  51:'Six Stage1 fields and all original transaction fields atomically update (explicit rule:68); remaining original fields defined in current 4/C12.',
  70:'Preserved diagnostic/identity payload names may omit i_/o_ prefixes; Stage1 fields cross current table55-60, D2_EXT is locally generated by stated S2 decoding:132, not a missing input.',
  111:'Single retained output buffer/reset/drain role; exact local-empty ownership defined in current 4.1:90-93. Buffer semantics directly support this role.',
 },
 'C14':{243:'Downstream single held transaction plus original data/metadata bit-identical forward rule in current 5.3; Stage1/golden fields inherited from 5.2 and C13.'},
 'C15':{461:'Current downstream output group together with explicitly mandatory same-name o_ metadata mapping (425 and429-457). Every forwarded field has an explicit input/output row.'},
 'C16':{
  396:'AMB scheduler chapter; shared 2 MHz clock/reset/lifecycle boundary and scheduler idle actual declaration and C18/PWI global drain semantics. No new external clock domain.',
  398:'Runtime enable/search mode plus START/STOP/abort context; counters reset on START/STOP:423-427 and actual scheduler clear branch. DCS stages expressly mandatory in9.4/9.6.',
  499:'Explicit bare amb_recheck_interval_frames default and enable condition; i_ boundary prefix inherited.',
  413:'Completed-NORMAL-frame counter/pending and paused-output role; 9.4 retains pending/busy and inhibits NORMAL throughout three-stage ownership.',
  434:'Current scheduler/control handshake group, actual six takeover conditions explicitly supplemented at432, AMB request/sample channel defined by9.4 and C10 calibration arbitration.',
  455:'Three-stage AMB/DC_R/DC_IR sequence, actual scheduler/control sample valid/ready/accepted/frame completion roles in C10 11.4 and current C17 sample interface.',
  489:'First numbered step of current full DC revalidation workflow 485-494; actual request/accept/done/failed handshake has current C10/C17/C18 definitions. Bare semantic names differ only by endpoint prefix.',
  471:'AMB result + mandatory two DCS stages; whole-sequence done/failed roles further fixed by9.4/9.6 and C18 completion conditions. AMB-only success is not sufficient.',
  140:'Explicit fork full generation/discard identity expansion and registered local-empty; common clock/reset stated in module responsibilities5.1. Existing conditional discard exemption not duplicated.',
  152:'Fork two held payload branches, independent handshakes and reset defined by5.1, full measurement payload in5.3 and explicit tracking table5.4. No missing port inference from abbreviated group title.',
 }
}
bad={1453:'Current source override resolves to historical-material exclusion, not analog-ready qualification; C03:150 and C02:94 explicitly define the real input.',
 2179:'Target467 is blank; actual bare amb_sequence_start is446.',2190:'Target467 is blank; actual bare amb_recheck_accept is442.',
 2894:'Source36 is upstream Router-to-overlap handshake; downstream i_result_ready is explicit in116.',
 2895:'Source36 is upstream Router-to-overlap handshake; downstream o_result_valid is explicit in116/121-123.',
 2996:'Source400 describes upstream i_result_valid/o_result_ready, opposite boundary; current downstream i_result_ready explicitly465.'}
for n in range(2619,2636):bad[n]='Current target is blank, ASCII connection diagram, unrelated owner-input/physical-input rule or fence; current exact port definition located independently below.'
for n in [2737,3120,3121,3122,3126,3127,3128]:bad[n]='Target is unrelated module list/diagram/TB exclusion/ADC owner inputs; current reset/control/completion boundary independently located below.'
for n in list(range(3129,3167))+[3188]:bad[n]='Source753 is physical ADC owner/start-eligibility chapter, not downstream formal measurement/discard definitions. Current6.7/6.10 explicitly separate these roles; no stale owner repair or hardware omission inferred.'
for n in range(3167,3182):bad[n]='Source370 is successful ADC completion table separator and three completion-sideband rows, not detection discard. Current6.10 explicit discard table defines that separate output group.'
fallback={'C01':{1453:('PPG_ACTIVE_V4_CONTROL_PLANE_INTEGRATION_WRAPPER_INTERFACE_CONTRACT.md',150)},
 'C10':{2737:('PPG_ADC_MEASUREMENT_AND_IDAC_INTEGRATION_WRAPPER_INTERFACE_CONTRACT.md',215)}}
def exact_def(code,name,filename,n):
 lines=cache[filename]
 hits=[(i,l) for i,l in enumerate(lines,1) if re.search(r'\b'+re.escape(name)+r'\b',l)]
 if hits:
  candidates=[x for x in hits if x[1].startswith('|')]
  i,l=(candidates or hits)[0];return dict(path='contracts/'+filename,line=i,text=l,form='literal_current_definition')
 if name.endswith('_high'):
  low=name[:-5]+'_low'
  hits=[(i,l) for i,l in enumerate(lines,1) if l.startswith('|') and token(low,l) and ('high' in l)]
  if hits:
   i,l=hits[0];return dict(path='contracts/'+filename,line=i,text=l,form='explicit_low_high_endpoint_pair')
 if code=='C16':
  bare=re.sub(r'^[io]_','',name)
  hits=[(i,l) for i,l in enumerate(lines,1) if l.startswith('|') and re.search(r'\b'+re.escape(bare)+r'\b',l)]
  assert hits,(code,name,n)
  i,l=hits[0];return dict(path='contracts/'+filename,line=i,text=l,form='explicit_bare_semantic_name')
 if n in fallback.get(code,{}):
  f,i=fallback[code][n];return dict(path='contracts/'+f,line=i,text=cache[f][i-1],form='explicit_related_boundary')
 # Sideband groups explicitly use `<TXN_ID>` and slash-expanded members.
 bare=re.sub(r'^(?:i_|o_)(?:measurement_result_discard_|detection_discard_|result_)','',name)
 hits=[(i,l) for i,l in enumerate(lines,1) if l.startswith('|') and (name.rsplit('_',1)[-1] in l) and ('discard' in l or 'TXN_ID' in l)]
 if 'discard' in name:
  i=next(i for i,l in enumerate(lines,1) if l.startswith('|') and ('o_detection_discard_' if 'detection' in name else 'o_measurement_result_discard_') in l)
  return dict(path='contracts/'+filename,line=i,text=lines[i-1],form='explicit_complete_discard_group')
 for related in ['PPG_PRECISION_WINDOW_CONTROLLER_INTERFACE_CONTRACT.md','PPG_PRECISION_WINDOW_INTEGRATION_WRAPPER_INTERFACE_CONTRACT.md','PPG_ACTIVE_V4_CONTROL_PLANE_INTEGRATION_WRAPPER_INTERFACE_CONTRACT.md']:
  hits=[(i,l) for i,l in enumerate(cache[related],1) if l.startswith('|') and re.search(r'\b'+re.escape(name)+r'\b',l)]
  if hits:
   i,l=hits[0];return dict(path='contracts/'+related,line=i,text=l,form='explicit_current_direct_child_definition')
 raise AssertionError(('missing current definition',code,name,n,hits))
# Negative controls validate what this register accepts: a current override must
# supersede stale prose; wrong heading/blank/opposite handshake are never accepted.
assert active_source('`ppg_system_integration/a.md:1` 当前`:2`')[1]==2
assert not token('i_b',scope(['## inputs','| i_a |','## outputs','| i_b |'],1))
assert not token('i_ready',scope(['| output | o_ready |',''],1))
assert not token('i_a',scope(['','| i_a |'],1))
assert {1453,2179,2190,2894,2895,2996,3167,3188}<=set(bad)
records=[];unresolved=[]
for r in inventory:
 code=r['contract'];n=int(r['line'])
 if code not in groups:continue
 c=[v.strip() for v in ml[n-1].split('|')];name=r['name'].strip('`');ref=active_source(c[2])
 assert c[1]==code and c[4].strip('`')==name and c[3]==r['direction']
 rec=dict(matrix_line=n,contract=code,port=name,direction=r['direction'],source_cell=c[2],
  rtl_modules=r['modules'],rtl_declaration_lines=r['declaration_lines'],reference=(ref[2] if ref else c[2]),
  anti_false_positive='Cross-module mechanisms and current normative group checked; known items and existing findings excluded from duplicate reporting.')
 if ref:
  path,ln,_=ref;filename=Path(path).name;lines=cache[filename];assert 1<=ln<=len(lines)
  rec.update(contract_path=path,contract_line=ln,target=lines[ln-1])
  if n in bad:
   try: definition=exact_def(code,name,filename,n)
   except AssertionError as error:unresolved.append(str(error));definition=None
   rec.update(state='confirmed_wrong_source_line',reason=bad[n],current_definition=definition)
  elif token(name,scope(lines,ln)):
   rec.update(state='accepted_literal_or_current_section',reason='Exact current port name occurs in cited line/table or named section, before any sibling heading; current override applied.')
  else:
   if ln not in groups[code]:unresolved.append(str(('unadjudicated group',code,n,name,ln,lines[ln-1])));continue
   rec.update(state='accepted_current_group_with_cross_contract_proof',reason=groups[code][ln])
 else:
  assert code=='C01' and n in (1468,1569,1570,1571),(code,n,c[2])
  rec.update(state='explicit_gap_or_historical_override_already_documented',reason=('Context-handover stall declared by current C09; row itself explicitly records C01 gap.' if n==1468 else 'Current matrix1571 expressly states C01 V1.16/4.2 now covers all three telemetry outputs and preserves old Source as historical pending housekeeping. Current C01:229 independently checked; known P2S limitation excluded.'))
 records.append(rec)
assert not unresolved,'\n'.join(unresolved)
assert len(records)==864 and collections.Counter(r['contract'] for r in records)==dict(C01=250,C10=288,C13=60,C14=63,C15=81,C16=122)
wrong=[r for r in records if r['state']=='confirmed_wrong_source_line'];assert len(wrong)==len(bad),(len(wrong),len(bad))
result=dict(reviewed_at=datetime.datetime.now().isoformat(timespec='seconds'),records=records,counts=dict(collections.Counter(r['state'] for r in records)),
 negative_controls=dict(current_override=True,neighbor_heading_excluded=True,opposite_handshake_rejected=True,blank_target_rejected=True),
 limits='Manual Source/category/index adjudication, using canonical Erie port inventory; not a second parser, not a reset/CDC/ASIC signoff. Cross-contract functional findings retain prior independent dynamic evidence.')
(O/'C01_C10_C13_C14_C15_C16_source_rows_864.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8')
f=E/'anchor_failures.csv';old=list(csv.DictReader(f.read_text(encoding='utf-8-sig').splitlines()));fields=list(old[0]);keys={(r['source'],int(r['line']),r['reference'],r['expected']) for r in old}
for r in wrong:
 row=dict(source='contracts/PPG_CONTRACT_CLOSURE_MATRIX.md',line=r['matrix_line'],reference=r['reference'],kind='active_contract_source',expected=r['port'],status='text_mismatch',target=r['target'])
 key=(row['source'],int(row['line']),row['reference'],row['expected'])
 if key not in keys:old.append(row);keys.add(key)
with f.open('w',encoding='utf-8',newline='') as fh:
 w=csv.DictWriter(fh,fieldnames=fields);w.writeheader();w.writerows(old)
print('MANUAL_SOURCE_BATCH',len(records),result['counts'],'NEW_CONFIRMED_INDEX_MISMATCHES',len(wrong))
